/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exemplotratamentotrycatch;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FramePrincipal extends javax.swing.JFrame {

    //Definindo variaveis
    private int num01;
    private int num02;
    private int resposta;

    //Creates new form FramePrincipal
    public FramePrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNum01 = new javax.swing.JTextField();
        tfNum02 = new javax.swing.JTextField();
        btSomar = new javax.swing.JButton();
        tfResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSomar.setText("Somar");
        btSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btSomar)
                    .addComponent(tfNum02, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(tfNum01)
                    .addComponent(tfResultado))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(tfNum01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfNum02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSomar)
                .addGap(18, 18, 18)
                .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed

        //Recebendo valores digitados
        String numeroUm = tfNum01.getText();
        String numeroDois = tfNum02.getText();

        try {
            //convertendo valores para inteiro
            num01 = Integer.parseInt(numeroUm);
            num02 = Integer.parseInt(numeroDois);

            resposta = num01 + num02;
            tfResultado.setText(String.valueOf(resposta));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "infomre números válidos!","Atenção", JOptionPane.ERROR_MESSAGE);
            
            System.out.println("Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_btSomarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSomar;
    private javax.swing.JTextField tfNum01;
    private javax.swing.JTextField tfNum02;
    private javax.swing.JTextField tfResultado;
    // End of variables declaration//GEN-END:variables
}
